server:
  port: 8080  # Port on which the server will run

  # Configure error handling
  error:
    include-message: always  # Include error message in error responses

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL JDBC driver class
    username: root  # MySQL database username
    url: jdbc:mysql://localhost:3306/user_db  # JDBC URL for connecting to the MySQL database
    password: EmanueL@15  # MySQL database password

  jpa:
    # Hibernate configuration
    hibernate:
      ddl-auto: update  # Automatically update the database schema based on entity classes
    show-sql: true  # Show SQL statements in the console
    open-in-view: true  # Enable "Open EntityManager in View" pattern for lazy loading
